version: '3.1'
services:
  stats-server:
    build: ./stat-service/server
    container_name: ewm_stats_service_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  stats-db:
    image: postgres:14-alpine
    container_name: ewm_stats_db_container
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  ewm-service:
    build: ./main-service
    container_name: ewm_main_service_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  ewm-db:
    image: postgres:14-alpine
    container_name: ewn_main_db_container
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
